name: single-cell-bioinformatics
dependencies:
- anaconda=custom=py35_0
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- bioconductor-annotate=1.48.0=1
- bioconductor-annotationdbi=1.32.3=0
- bioconductor-biobase=2.30.0=0
- bioconductor-biocgenerics=0.16.1=r3.2.2_0
- bioconductor-genefilter=1.52.1=r3.2.2_0
- bioconductor-iranges=2.4.8=0
- bioconductor-s4vectors=0.8.11=0
- bioconductor-sva=3.15.0=0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- gsl=1.16=2
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_0
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libgcc=4.8.5=1
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=1
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- ncurses=5.9=1
- notebook=4.2.0=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=0
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- patsy=0.4.1=py35_0
- pcre=8.31=0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.2.1=py35_0
- r=3.2.2=0
- r-base=3.2.2=0
- r-boot=1.3_17=r3.2.2_0a
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-dbi=0.3.1=r3.2.2_3a
- r-foreign=0.8_66=r3.2.2_0a
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-lattice=0.20_33=r3.2.2_0a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-mgcv=1.8_9=r3.2.2_0a
- r-nlme=3.1_122=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-rpart=4.1_10=r3.2.2_0a
- r-rsqlite=1.0.0=r3.2.2_1a
- r-spatial=7.3_11=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-xml=3.98_1.3=r3.2.2_0a
- r-xtable=1.8_0=r3.2.2_0a
- readline=6.2=2
- rpy2=2.7.8=py35r3.2.2_1
- scikit-learn=0.17.1=np111py35_1
- scipy=0.17.1=np111py35_0
- seaborn=0.7.0=py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xlrd=0.9.4=py35_0
- xz=5.0.5=1
- zlib=1.2.8=1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - fastcluster==1.1.20
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0

